version: '3.7'

services:
  nginx:
    build:
      context: docker/nginx
    depends_on:
    - fpm
    - frontend

  frontend:
    image: node:16-alpine3.15
    command: sh -c "npm install && npm run serve"
    working_dir: /var/www/app
    #build: context: docker/frontend
    volumes:
    - ./frontend:/var/www/app

  fpm:
    build:
      context: docker/fpm
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: "http://localhost" # @TODO: fix it
      APP_KEY: ${APP_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
    depends_on:
    - db
    volumes:
    - ./backend:/var/www/app

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlroot}
      MYSQL_DATABASE: ${MYSQL_ROOT_PASSWORD:-laravel}
      MYSQL_USER: ${MYSQL_ROOT_PASSWORD:-laravel}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD:-laravel}
    volumes:
    - db:/var/lib/mysql

volumes:
  db:
    driver: local